kubernetes_kubelet_extra_args: ""
kubernetes_kubeadm_init_extra_opts: ""
kubernetes_join_command_extra_opts: ""

kubernetes_allow_pods_on_master: true
kubernetes_enable_web_ui: true
kubernetes_version: '1.18.0-00'

kubernetes_pod_network:
    # Flannel CNI.
    #cni: 'flannel'
    #cidr: '10.244.0.0/16'
    # Calico CNI.
    cni: 'calico'
    cidr: '192.168.0.0/16'

kubernetes_apiserver_advertise_address: ''
kubernetes_version_kubeadm: 'stable-{{ kubernetes_version }}'
kubernetes_ignore_preflight_errors: 'all'

kubernetes_calico_manifest_file: https://docs.projectcalico.org/v3.10/manifests/calico.yaml